site_name: BOSH
theme:
    name: mkdocs
    custom_dir: bosh_theme
pages:
- Home: 'index.md'
- Guides: 
  - Overview: 'guides/overview.md'
  - Setting up the BOSH CLI: 'guides/lab-1.md'
  - Examining a BOSH Stemcell: 'guides/lab-2.md'
  - Upload a BOSH Stemcell: 'guides/lab-3.md'
  - Create and Upload a BOSH Cloud-Config: 'guides/lab-4.md'
  - Upload a BOSH Release: 'guides/lab-5.md'
  - Examine a BOSH Release: 'guides/lab-6.md'
  - Deploying a BOSH Release: 'guides/lab-7.md'
  - Accessing a BOSH Managed Instance: 'guides/lab-8.md'
  - BOSH Instance Internals: 'guides/lab-9.md'
  - Reconfiguring BOSH Deployments: 'guides/lab-10.md'
  - Authoring a BOSH Release: 'guides/lab-11.md'
  - Deploy Zookeeper: 'guides/lab-12.md'
  - BOSH Errands: 'guides/lab-13.md'
  - BOSH Release Upgrades: 'guides/lab-14.md'
  - BOSH Runtime-Config & Add-ons: 'guides/lab-15.md'
  - BOSH Stemcell Upgrades: 'guides/lab-16.md'
- Resources: 
  - Overview: 'resources/overview.md'
  - Releases: 'resources/releases.md'
  - Stemcells: 'resources/stemcells.md'
- Docs: 
  - Overview: 'docs/overview.md'
extra_css: [css/extra.css]
extra:
    version: 0.0.1
    links:
        - https://bosh.io